//
// Generated file, do not edit! Created by opp_msgtool 6.0 from inet/HiNA/Messages/PCN/CNP.msg.
//

#ifndef __INET_CNP_M_H
#define __INET_CNP_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class CNP;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Class generated from <tt>inet/HiNA/Messages/PCN/CNP.msg:7</tt> by opp_msgtool.
 * <pre>
 * class CNP extends FieldsChunk
 * {
 *     chunkLength = b(32);
 *     uint32_t RecRate;
 * }
 * </pre>
 */
class INET_API CNP : public ::inet::FieldsChunk
{
  protected:
    uint32_t RecRate = 0;

  private:
    void copy(const CNP& other);

  protected:
    bool operator==(const CNP&) = delete;

  public:
    CNP();
    CNP(const CNP& other);
    virtual ~CNP();
    CNP& operator=(const CNP& other);
    virtual CNP *dup() const override {return new CNP(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual uint32_t getRecRate() const;
    virtual void setRecRate(uint32_t RecRate);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CNP& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CNP& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::CNP *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::CNP*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_CNP_M_H

