//
// Generated file, do not edit! Created by opp_msgtool 6.0 from inet/HiNA/Messages/PfcFrame/EthernetPfcFrame.msg.
//

#ifndef __INET_ETHERNETPFCFRAME_M_H
#define __INET_ETHERNETPFCFRAME_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class EthernetPfcFrame;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/linklayer/ethernet/common/EthernetControlFrame_m.h" // import inet.linklayer.ethernet.common.EthernetControlFrame


namespace inet {

/**
 * Enum generated from <tt>inet/HiNA/Messages/PfcFrame/EthernetPfcFrame.msg:14</tt> by opp_msgtool.
 * <pre>
 * enum EthernetPfcControlOpCode
 * {
 *     ETHERNET_PFC_PAUSE = 3;
 *     ETHERNET_PFC_RESUME = 4;
 * }
 * </pre>
 */
enum EthernetPfcControlOpCode {
    ETHERNET_PFC_PAUSE = 3,
    ETHERNET_PFC_RESUME = 4
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const EthernetPfcControlOpCode& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, EthernetPfcControlOpCode& e) { int n; b->unpack(n); e = static_cast<EthernetPfcControlOpCode>(n); }

/**
 * Class generated from <tt>inet/HiNA/Messages/PfcFrame/EthernetPfcFrame.msg:20</tt> by opp_msgtool.
 * <pre>
 * class EthernetPfcFrame extends EthernetControlFrameBase
 * {
 *     chunkLength = B(20);
 *     int16_t priority = -1;
 *     int16_t pauseTime = 100; // in 512 bit-time units
 * }
 * </pre>
 */
class INET_API EthernetPfcFrame : public ::inet::EthernetControlFrameBase
{
  protected:
    int16_t priority = -1;
    int16_t pauseTime = 100;

  private:
    void copy(const EthernetPfcFrame& other);

  protected:
    bool operator==(const EthernetPfcFrame&) = delete;

  public:
    EthernetPfcFrame();
    EthernetPfcFrame(const EthernetPfcFrame& other);
    virtual ~EthernetPfcFrame();
    EthernetPfcFrame& operator=(const EthernetPfcFrame& other);
    virtual EthernetPfcFrame *dup() const override {return new EthernetPfcFrame(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int16_t getPriority() const;
    virtual void setPriority(int16_t priority);

    virtual int16_t getPauseTime() const;
    virtual void setPauseTime(int16_t pauseTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const EthernetPfcFrame& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, EthernetPfcFrame& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::EthernetPfcFrame *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::EthernetPfcFrame*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_ETHERNETPFCFRAME_M_H

