//
// Generated file, do not edit! Created by opp_msgtool 6.0 from inet/HiNA/Messages/BFCTag/isPause.msg.
//

#ifndef __INET_ISPAUSE_M_H
#define __INET_ISPAUSE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class isPause;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/TagBase_m.h" // import inet.common.TagBase

#include "inet/common/Units_m.h" // import inet.common.Units


namespace inet {

/**
 * Class generated from <tt>inet/HiNA/Messages/BFCTag/isPause.msg:22</tt> by opp_msgtool.
 * <pre>
 * class isPause extends TagBase
 * {
 *     bool bfcisPause; //记录当前数据包是否是暂停数据包
 * }
 * </pre>
 */
class INET_API isPause : public ::inet::TagBase
{
  protected:
    bool bfcisPause = false;

  private:
    void copy(const isPause& other);

  protected:
    bool operator==(const isPause&) = delete;

  public:
    isPause();
    isPause(const isPause& other);
    virtual ~isPause();
    isPause& operator=(const isPause& other);
    virtual isPause *dup() const override {return new isPause(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual bool getBfcisPause() const;
    virtual void setBfcisPause(bool bfcisPause);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const isPause& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, isPause& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::isPause *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::isPause*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_ISPAUSE_M_H

