//
// Generated file, do not edit! Created by opp_msgtool 6.0 from inet/HiNA/Messages/POSEIDON/PSDINTHeader.msg.
//

#ifndef __INET_INET_HINA_MESSAGES_POSEIDON_PSDINTHEADER_M_H
#define __INET_INET_HINA_MESSAGES_POSEIDON_PSDINTHEADER_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class PSDINTHeader;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Class generated from <tt>inet\HiNA\Messages\POSEIDON\PSDINTHeader.msg:21</tt> by opp_msgtool.
 * <pre>
 * class PSDINTHeader extends FieldsChunk
 * {
 *     chunkLength = B (2);
 *     omnetpp::simtime_t TS;	//时间戳
 *     omnetpp::simtime_t MPD;	//时间戳
 *     //double txRate;			//端口的速率
 *    // uint64 txBytes;				//byte= 8 bit
 *     //omnetpp::simtime_t TS2;	//时间戳
 * }
 * </pre>
 */
class INET_API PSDINTHeader : public ::inet::FieldsChunk
{
  protected:
    ::omnetpp::simtime_t TS = SIMTIME_ZERO;
    ::omnetpp::simtime_t MPD = SIMTIME_ZERO;

  private:
    void copy(const PSDINTHeader& other);

  protected:
    bool operator==(const PSDINTHeader&) = delete;

  public:
    PSDINTHeader();
    PSDINTHeader(const PSDINTHeader& other);
    virtual ~PSDINTHeader();
    PSDINTHeader& operator=(const PSDINTHeader& other);
    virtual PSDINTHeader *dup() const override {return new PSDINTHeader(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual ::omnetpp::simtime_t getTS() const;
    virtual void setTS(::omnetpp::simtime_t TS);

    virtual ::omnetpp::simtime_t getMPD() const;
    virtual void setMPD(::omnetpp::simtime_t MPD);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PSDINTHeader& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PSDINTHeader& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::PSDINTHeader *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::PSDINTHeader*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_INET_HINA_MESSAGES_POSEIDON_PSDINTHEADER_M_H

