//
// Generated file, do not edit! Created by opp_msgtool 6.0 from inet/HiNA/Messages/BfcCNP/EthernetBfcCNP.msg.
//

#ifndef __INET_ETHERNETBFCCNP_M_H
#define __INET_ETHERNETBFCCNP_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class EthernetBfcCNPFrame;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk

#include "inet/linklayer/ethernet/common/EthernetControlFrame_m.h" // import inet.linklayer.ethernet.common.EthernetControlFrame


namespace inet {

/**
 * Enum generated from <tt>inet/HiNA/Messages/BfcCNP/EthernetBfcCNP.msg:22</tt> by opp_msgtool.
 * <pre>
 * enum EthernetBfcCNPOpCode
 * {
 *     ETHERNET_BFC_DECELERATION = 5;
 *     ETHERNET_BFC_SPEEDUP = 6;
 * }
 * </pre>
 */
enum EthernetBfcCNPOpCode {
    ETHERNET_BFC_DECELERATION = 5,
    ETHERNET_BFC_SPEEDUP = 6
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const EthernetBfcCNPOpCode& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, EthernetBfcCNPOpCode& e) { int n; b->unpack(n); e = static_cast<EthernetBfcCNPOpCode>(n); }

/**
 * Class generated from <tt>inet/HiNA/Messages/BfcCNP/EthernetBfcCNP.msg:28</tt> by opp_msgtool.
 * <pre>
 * class EthernetBfcCNPFrame extends EthernetControlFrameBase
 * {
 *     chunkLength = B(20);
 *     int16_t queueID = -1;
 *     int16_t pauseTime = 100; // in 512 bit-time units
 * }
 * </pre>
 */
class INET_API EthernetBfcCNPFrame : public ::inet::EthernetControlFrameBase
{
  protected:
    int16_t queueID = -1;
    int16_t pauseTime = 100;

  private:
    void copy(const EthernetBfcCNPFrame& other);

  protected:
    bool operator==(const EthernetBfcCNPFrame&) = delete;

  public:
    EthernetBfcCNPFrame();
    EthernetBfcCNPFrame(const EthernetBfcCNPFrame& other);
    virtual ~EthernetBfcCNPFrame();
    EthernetBfcCNPFrame& operator=(const EthernetBfcCNPFrame& other);
    virtual EthernetBfcCNPFrame *dup() const override {return new EthernetBfcCNPFrame(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int16_t getQueueID() const;
    virtual void setQueueID(int16_t queueID);

    virtual int16_t getPauseTime() const;
    virtual void setPauseTime(int16_t pauseTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const EthernetBfcCNPFrame& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, EthernetBfcCNPFrame& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::EthernetBfcCNPFrame *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::EthernetBfcCNPFrame*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_ETHERNETBFCCNP_M_H

