//
// Generated file, do not edit! Created by opp_msgtool 6.0 from inet/HiNA/Messages/HiTag/HiTag.msg.
//

#ifndef __INET_INET_HINA_MESSAGES_HITAG_HITAG_M_H
#define __INET_INET_HINA_MESSAGES_HITAG_HITAG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class HiTag;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/TagBase_m.h" // import inet.common.TagBase

#include "inet/common/Units_m.h" // import inet.common.Units

#include "inet/networklayer/common/L3Address_m.h" // import inet.networklayer.common.L3Address


namespace inet {

/**
 * Class generated from <tt>inet\HiNA\Messages\HiTag\HiTag.msg:14</tt> by opp_msgtool.
 * <pre>
 * class HiTag extends TagBase
 * {
 *     uint32_t Priority = -1;//防止没设置优先级的包进入优先级队列
 *     uint64_t PacketId;
 *     uint64_t FirstRttPcks;
 *     uint32_t FlowId;
 *     uint64_t FlowSize;
 *     uint64_t PacketSize;
 *     bool reverse = false;//信用协议反向路由用
 *     simtime_t creationtime;
 *     bool isLastPck = false;
 *     uint32_t senderPriority = -1;//for HOMA
 * 
 *     //for PFC
 *     int16_t op;
 *     int16_t interfaceId;
 * 
 *     //for BCN 
 *     bool isDeceleration;
 *     bool isSpeedup;
 *     inet::L3Address destAddr;
 *     inet::L3Address srcAddr;
 *     int16_t local_interfaceId; //记录本地mac端口
 *     int bfccnpECN;//用于判断发送的cnp包是否处于拥塞交换机处
 * 
 *     //for BFC
 *     uint32_t queueID; //定向在app，flowid % queueNum 写死。
 *     uint32_t upstreamQueueID;
 *     bool ispausePck;
 * 
 * }
 * </pre>
 */
class INET_API HiTag : public ::inet::TagBase
{
  protected:
    uint32_t Priority = -1;
    uint64_t PacketId = 0;
    uint64_t FirstRttPcks = 0;
    uint32_t FlowId = 0;
    uint64_t FlowSize = 0;
    uint64_t PacketSize = 0;
    bool reverse = false;
    ::omnetpp::simtime_t creationtime = SIMTIME_ZERO;
    bool isLastPck_ = false;
    uint32_t senderPriority = -1;
    int16_t op = 0;
    int16_t interfaceId = 0;
    bool isDeceleration_ = false;
    bool isSpeedup_ = false;
    L3Address destAddr;
    L3Address srcAddr;
    int16_t local_interfaceId = 0;
    int bfccnpECN = 0;
    uint32_t queueID = 0;
    uint32_t upstreamQueueID = 0;
    bool ispausePck = false;

  private:
    void copy(const HiTag& other);

  protected:
    bool operator==(const HiTag&) = delete;

  public:
    HiTag();
    HiTag(const HiTag& other);
    virtual ~HiTag();
    HiTag& operator=(const HiTag& other);
    virtual HiTag *dup() const override {return new HiTag(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual uint32_t getPriority() const;
    virtual void setPriority(uint32_t Priority);

    virtual uint64_t getPacketId() const;
    virtual void setPacketId(uint64_t PacketId);

    virtual uint64_t getFirstRttPcks() const;
    virtual void setFirstRttPcks(uint64_t FirstRttPcks);

    virtual uint32_t getFlowId() const;
    virtual void setFlowId(uint32_t FlowId);

    virtual uint64_t getFlowSize() const;
    virtual void setFlowSize(uint64_t FlowSize);

    virtual uint64_t getPacketSize() const;
    virtual void setPacketSize(uint64_t PacketSize);

    virtual bool getReverse() const;
    virtual void setReverse(bool reverse);

    virtual ::omnetpp::simtime_t getCreationtime() const;
    virtual void setCreationtime(::omnetpp::simtime_t creationtime);

    virtual bool isLastPck() const;
    virtual void setIsLastPck(bool isLastPck);

    virtual uint32_t getSenderPriority() const;
    virtual void setSenderPriority(uint32_t senderPriority);

    virtual int16_t getOp() const;
    virtual void setOp(int16_t op);

    virtual int16_t getInterfaceId() const;
    virtual void setInterfaceId(int16_t interfaceId);

    virtual bool isDeceleration() const;
    virtual void setIsDeceleration(bool isDeceleration);

    virtual bool isSpeedup() const;
    virtual void setIsSpeedup(bool isSpeedup);

    virtual const L3Address& getDestAddr() const;
    virtual L3Address& getDestAddrForUpdate() { return const_cast<L3Address&>(const_cast<HiTag*>(this)->getDestAddr());}
    virtual void setDestAddr(const L3Address& destAddr);

    virtual const L3Address& getSrcAddr() const;
    virtual L3Address& getSrcAddrForUpdate() { return const_cast<L3Address&>(const_cast<HiTag*>(this)->getSrcAddr());}
    virtual void setSrcAddr(const L3Address& srcAddr);

    virtual int16_t getLocal_interfaceId() const;
    virtual void setLocal_interfaceId(int16_t local_interfaceId);

    virtual int getBfccnpECN() const;
    virtual void setBfccnpECN(int bfccnpECN);

    virtual uint32_t getQueueID() const;
    virtual void setQueueID(uint32_t queueID);

    virtual uint32_t getUpstreamQueueID() const;
    virtual void setUpstreamQueueID(uint32_t upstreamQueueID);

    virtual bool getIspausePck() const;
    virtual void setIspausePck(bool ispausePck);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const HiTag& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, HiTag& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::HiTag *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::HiTag*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_INET_HINA_MESSAGES_HITAG_HITAG_M_H

