//
// Generated file, do not edit! Created by opp_msgtool 6.0 from inet/HiNA/Messages/BFCHeader/BFCHeader.msg.
//

#ifndef __INET_BFCHEADER_M_H
#define __INET_BFCHEADER_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

class BFCHeader;

}  // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs

#include "inet/common/packet/chunk/Chunk_m.h" // import inet.common.packet.chunk.Chunk


namespace inet {

/**
 * Class generated from <tt>inet/HiNA/Messages/BFCHeader/BFCHeader.msg:21</tt> by opp_msgtool.
 * <pre>
 * class BFCHeader extends FieldsChunk
 * {
 *     chunkLength = B (8);
 *     int QueueID;
 *     int UpstreamQueueID;
 * 
 * }
 * </pre>
 */
class INET_API BFCHeader : public ::inet::FieldsChunk
{
  protected:
    int QueueID = 0;
    int UpstreamQueueID = 0;

  private:
    void copy(const BFCHeader& other);

  protected:
    bool operator==(const BFCHeader&) = delete;

  public:
    BFCHeader();
    BFCHeader(const BFCHeader& other);
    virtual ~BFCHeader();
    BFCHeader& operator=(const BFCHeader& other);
    virtual BFCHeader *dup() const override {return new BFCHeader(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getQueueID() const;
    virtual void setQueueID(int QueueID);

    virtual int getUpstreamQueueID() const;
    virtual void setUpstreamQueueID(int UpstreamQueueID);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BFCHeader& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BFCHeader& obj) {obj.parsimUnpack(b);}


}  // namespace inet


namespace omnetpp {

template<> inline inet::BFCHeader *fromAnyPtr(any_ptr ptr) { return check_and_cast<inet::BFCHeader*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __INET_BFCHEADER_M_H

